#!/bin/bash

POTENTIAL_TOKENS=$(xclip -o)
SCRIPT_FILE=$(basename "$0")
FILE_NO_EXT="${SCRIPT_FILE%.*}"
export DISPLAY=:0.0

[[ -z $POTENTIAL_TOKENS ]] && notify-send "$FILE_NO_EXT" "No tokens found in clipboard" && exit 1
[[ $(wc -l <<<"$POTENTIAL_TOKENS") -ne 4 ]] && notify-send "$FILE_NO_EXT" "Something went wrong, normally there should be 4 lines in clipboard" && exit 1

echo "$POTENTIAL_TOKENS" | tr ' ' '\n' >~/.aws/credentials
[[ -f "$HOME/.aws/const_credentials" ]] && cat "$HOME"/.aws/const_credentials >>~/.aws/credentials